services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network

  portfolio:
    build: .
    container_name: portfolio
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
